export const REVISION_FILE_RULE_KEYS = [
  'code',
  'type',
  'name',
  'description',
  'spec',
  'keywordCodes',
  'mechanic',
  'mechanicPayload',
  'contentStatus',
  'contentNote',
  'active',
  'catalogSection',
  'catalogSortOrder',
] as const;
